### ISSUE TITLE
Also encountered the same problem. 

### ISSUE THREAD

**Issue by axis0093** [nickilanjelo/LazyColumnCapturedScroll#1]
Hi nickilanjelo,

I'm sorry to bother you, but I also encountered this problem.

I searched on issuetracker.google.com and found the BUG you mentioned, and also found this repository.

I think this issue is related to the Overscroll of LazyColumn. After setting the LocalOverscrollConfiguration to null, the LazyColumn no longer has the Overscroll animation, and the problem disappeared. I suspect it might be because the Overscroll animation hadn't finished before another scroll was triggered consecutively.

Do you have a better solution? 

Thank you.

**Comment by nickilanjelo** [comment]
@axis0093 Hi! Sorry for the long answer, I've finally reached the repo. Seems that your fix helps, I've pushed changes containing logic for LocalOverscollConfiguration change, and now I don't encounter the problem. Huge thanks for your suggestion! I'm going to convey this information to the corresponding issue, and I hope that it would help fixing the bug to eliminate usage of any workaround.

**Comment by nickilanjelo** [comment]
Fixed in https://github.com/nickilanjelo/LazyColumnCapturedScroll/commit/0acc3716aed48537992a0c0f309ece3f615a7fd9
